apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: postgres-timescale:5432
    database: quantumedge
    user: qe_user
    secureJsonData:
      password: qe_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
